package ru.stqa.pft.addressbook;// Generated by Selenium IDE

import org.testng.annotations.Test;

public class addNewUser extends TestBaseClone
{

    @Test
    public void untitled() {
        gotoUserPage();
        inetUserCreation();
        fillUserForm(new UserData("Starovoytov", "Igor", "Victorovich", "SKLN", "idsys", "Tver", "89301530042", "bficrew@mail.ru"));
    }

}
