package ru.stqa.pft.addressbook;// Generated by Selenium IDE
import org.testng.annotations.Test;

public class DeleteUserTest extends TestBaseClone{

   @Test
  public void deleteUser() {
     clickButtonHome();
     clickDeleteUser();
     clickButtonHome();
  }

}


