package ru.stqa.pft.addressbook;// Generated by Selenium IDE

import org.testng.annotations.Test;

public class GroupCreationTests extends TestBase {

    @Test
    public void testGroupCreation() {
        gotoGroupPage();
        initGroupeCreation();
        fillGroupForm(new GroupData("test5", "test6", "test7"));
        sumbitGroupeCreation();
        returnToGroupe();
    }

}
