package ru.stqa.pft.addressbook.tests;// Generated by Selenium IDE

import org.testng.annotations.Test;
import ru.stqa.pft.addressbook.model.GroupData;

public class GroupCreationTests extends TestBase {

    @Test
    public void testGroupCreation() {
        app.gotoGroupPage();
        app.initGroupeCreation();
        app.fillGroupForm(new GroupData("test5", "test6", "test7"));
        app.sumbitGroupeCreation();
        app.returnToGroupe();
    }

}
